### ISSUE TITLE
Any plans for a CMS?

### ISSUE THREAD

**Issue by angelxmoreno** [rannmann/Idle-Heroes-RDB#1]
The data seems solid. Do you need help building a CMS where users can edit and add more?

**Comment by rannmann** [comment]
I haven't played idle heroes in some time.  I'm not really planning on doing any more with this project, sorry.  You're welcome to download the CSVs and edit them as a type of CMS, then write a quick script to dump new CSV rows into SQL via INSERT IGNORE.

**Comment by angelxmoreno** [comment]
Cool. I will. could you make me an admin of this repo? I can take over the project and reference you
